### ISSUE TITLE
Test workflow

### ISSUE THREAD

**Issue by nicola-calonaci** [caravagnalab/nf-evoverse#12]
Set-up single module level tests using `nf-test`.

- [ ] Generate template for the simplest module (`annotate_driver`) @tucano :
    - [ ] Switch to external R script and rely on `nextflow template`

**Comment by RodTol** [comment]
- Create basic process.success for all the modules: (Rodolfo)
  - [x] getposition
  - [x] joinposition
  - [x] tinc
  - [x] pyclone
  - [x] Viber
  - [x] ctree:
  - [x] SparseSignature wip
  - [x] SigProfiler wip

- [x] Test dataset: we need bam files to test the lifter
- [x] Make the tests for the local subworkflows  (@brandon-hastings )
  - [x] Formatter
  - [x] Lifter
      - need bam and bai files to complete
  - [x] Driver Annotation
  - [x] QC
  - [x] Subclonal Deconvolution
  - [x] Signature Deconvolution
 
- Leave snapshot check commented, until we have the full test dataset 
- [x] Review paths to test data files
